clc
clear all 
close all
%%% This example is an illustarion of the application of LDA on data
%%% generated using Gaussian mixture models or uniform mixuture models with
%%% different dimensionalities.
%%% PDF parameters are selected first, then data is generated from a
%%% mixture of PDFs. projection vectors are later generated by performing LDA
%%% on generated data, then data is projected on the projection vector and plotted.

%%% Gaussian distribution case %%%
%% Generate two datasets from two different gaussian distributions/categories

%% 1st data category
N1=1000; %specify number of samples of each category
pdfParameters.Mean=[5;1];% normal distribution mean
pdfParameters.Cov=[1 -1.5; -1.5 3];% normal distribution Covariance
pdfParameters.type='Gaussian';
n = size(pdfParameters.Mean,1); % Determine data dimensionality

%generate N points of random samples from pdf N(pdfParameters.Mean,pdfParameters.Cov))
x1=generateRandomSamples(N1,n,pdfParameters,0);


%% 2nd data category
clear pdfParameters n
N2=1300; %specify number of samples of each category
pdfParameters.Mean=[-1;-3];% normal distribution mean
pdfParameters.Cov=[5 -.5; -.5 10];% normal distribution Covariance
pdfParameters.type='Gaussian';
n = size(pdfParameters.Mean,1);% Determine data dimensionality

%generate N points of random samples from pdf N(pdfParameters.Mean,pdfParameters.Cov))
x2=generateRandomSamples(N2,n,pdfParameters,0);

x = [x1,x2]; labels = [ones(1,N1),2*ones(1,N2)];
%% Determine LDA vector and data projected on it
[w,y]=performLDA(x,labels);

% find where each labeled data is projected
y1 = y(find(labels==1)); y2 = y(find(labels==2));
%% plot 
% Plot the data before and after linear projection
figure(1),
subplot(2,1,1), plot(x1(1,:),x1(2,:),'r*'); hold on;
plot(x2(1,:),x2(2,:),'bo'); axis equal, 
subplot(2,1,2), plot(y1(1,:),zeros(1,N1),'r*'); hold on;
plot(y2(1,:),zeros(1,N2),'bo'); axis equal,



%%%Uniform Distributions case %%%
%% Generate two datasets from two different uniform distributions categories

%% 1st data category
clear pdfParameters n
N1=1000; %specify number of samples of each category
%store parameters in a structure
pdfParameters.a=[-5 ;1];%uniform distribution lower endpoints of the x and y axis
pdfParameters.b=[-1; 5 ] ; %uniform distributions higher endpoint of the x and y axis
pdfParameters.Scale=(pdfParameters.b-pdfParameters.a)/2;
pdfParameters.Mean=(pdfParameters.a+pdfParameters.b)/2;
pdfParameters.type='Uniform';
n = size(pdfParameters.a,1); % Data dimensionality


%generate N points of random samples from pdf N(pdfParameters.Mean,pdfParameters.Cov))
x1=generateRandomSamples(N1,n,pdfParameters,0);


%% 2nd data category
clear pdfParameters n
N2=1300; %specify number of samples of each category
%store parameters in a structure
pdfParameters.a=[1 ;5];%uniform distribution lower endpoints of the x and y axis
pdfParameters.b=[5; 10 ] ; %uniform distributions higher endpoint of the x and y axis
pdfParameters.Scale=(pdfParameters.b-pdfParameters.a)/2;
pdfParameters.Mean=(pdfParameters.a+pdfParameters.b)/2;
pdfParameters.type='Uniform';
n = size(pdfParameters.a,1); % Data dimensionality

%generate N points of random samples from pdf N(pdfParameters.Mean,pdfParameters.Cov))
x2=generateRandomSamples(N2,n,pdfParameters,0);

x = [x1,x2]; labels = [ones(1,N1),2*ones(1,N2)];
%% Determine LDA vector and data projected on it
[w,y]=performLDA(x,labels);

% find where each labeled data is projected
y1 = y(find(labels==1)); y2 = y(find(labels==2));
%% plot 
% Plot the data before and after linear projection
figure(2),
subplot(2,1,1), plot(x1(1,:),x1(2,:),'r*'); hold on;
plot(x2(1,:),x2(2,:),'bo'); axis equal, 
subplot(2,1,2), plot(y1(1,:),zeros(1,N1),'r*'); hold on;
plot(y2(1,:),zeros(1,N2),'bo'); axis equal,
